USE [master]
GO

/****** Object:  Database [AndreiDragulin]    Script Date: 7/1/2020 10:04:40 PM ******/
CREATE DATABASE [AndreiDragulin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AndreiDragulin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVERLICENTA\MSSQL\DATA\AndreiDragulin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AndreiDragulin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVERLICENTA\MSSQL\DATA\AndreiDragulin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AndreiDragulin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AndreiDragulin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AndreiDragulin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AndreiDragulin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AndreiDragulin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AndreiDragulin] SET ARITHABORT OFF 
GO

ALTER DATABASE [AndreiDragulin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AndreiDragulin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AndreiDragulin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AndreiDragulin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AndreiDragulin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AndreiDragulin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AndreiDragulin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AndreiDragulin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AndreiDragulin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AndreiDragulin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AndreiDragulin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AndreiDragulin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AndreiDragulin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AndreiDragulin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AndreiDragulin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AndreiDragulin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AndreiDragulin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AndreiDragulin] SET RECOVERY FULL 
GO

ALTER DATABASE [AndreiDragulin] SET  MULTI_USER 
GO

ALTER DATABASE [AndreiDragulin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AndreiDragulin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AndreiDragulin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AndreiDragulin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AndreiDragulin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AndreiDragulin] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AndreiDragulin] SET  READ_WRITE 
GO

